FROM node:20-alpine AS build
WORKDIR /app
COPY hospital-management-frontend/package*.json ./
RUN npm ci
COPY hospital-management-frontend/ .
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/hospital-management-frontend /usr/share/nginx/html
COPY Docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
